# Site settings
title: 郁盛杰的博客
email: aoto_yu@163.com
description: "技术、学习"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aoto.github.io" # the base hostname & protocol for your site
twitter_username: aotostar
github_username:  aoto

# Build settings
markdown: kramdown
